// @ts-check
import { defineConfig, envField } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import cloudflare from '@astrojs/cloudflare';
import redirectGenerator from './src/integrations/redirectGenerator.ts';
import csvBuildPlugin from './src/integrations/csvBuildPlugin.ts';

// https://astro.build/config
export default defineConfig({
  site: 'https://crimehotspots.com',
  trailingSlash: 'always',
  output: 'server',
  adapter: cloudflare({
    imageService: 'passthrough', // Use Astro's default image service
  }),
  integrations: [
    csvBuildPlugin(),
    // @astrojs/sitemap removed — we use custom SSR sitemaps (sitemap-0.xml.ts,
    // sitemap-index.xml.ts) that query D1 at runtime so crime pages are included.
    // The static sitemap generated by @astrojs/sitemap only contained ~208 static
    // pages and overwrote our dynamic SSR route, starving Google of 2,000+ URLs.
    redirectGenerator(),
  ],
  env: {
    schema: {
      BUTTONDOWN_API_KEY: envField.string({ context: 'server', access: 'secret', optional: true }),
      PUBLIC_SAFETY_TIPS_GAS_URL: envField.string({ context: 'client', access: 'public', optional: true }),
    }
  },
  vite: {
    plugins: [tailwindcss()]
  }
});