name = "crime-hotspots"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "crimehotspots.com/*", zone_name = "crimehotspots.com" },
  { pattern = "www.crimehotspots.com/*", zone_name = "crimehotspots.com" }
]

[assets]
directory = "./dist/client/"
not_found_handling = "404-page"

[[d1_databases]]
binding = "DB"
database_name = "crime-hotspots-db"
database_id = "23311480-68d6-45ec-b351-e6185a5af80a"
