name = "crime-sync"
main = "index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "crime-hotspots-db"
database_id = "23311480-68d6-45ec-b351-e6185a5af80a"

[triggers]
crons = ["0 10 * * *"]   # Daily 10:00 UTC (6:00 AM Trinidad)
