// src/js/blog.js
import { renderHeader } from './components/header.js';

// Blog post metadata (this will be auto-generated by GitHub Actions)
// In production, this file will be generated from markdown frontmatter
const blogPosts = [
  {
    id: 'trinidad-weekly-2025-11-10',
    title: 'Trinidad & Tobago Weekly Crime Report - November 10, 2025',
    country: 'tt',
    countryName: 'Trinidad & Tobago',
    date: '2025-11-10',
    excerpt: 'Analysis of 47 crime incidents reported this week. Murder rate decreased 12% compared to last week, while robbery incidents increased in Port of Spain area.',
    author: 'Crime Hotspots Analytics',
    readTime: '4 min read',
    image: '/assets/images/trinidad.jpg',
    slug: 'trinidad-weekly-2025-11-10',
    tags: ['Trinidad', 'Weekly Report', 'Statistics']
  },
  {
    id: 'guyana-weekly-2025-11-10',
    title: 'Guyana Weekly Crime Report - November 10, 2025',
    country: 'gy',
    countryName: 'Guyana',
    date: '2025-11-10',
    excerpt: 'Analysis of 23 crime incidents reported this week. Georgetown saw a spike in theft incidents, particularly in the Stabroek Market area.',
    author: 'Crime Hotspots Analytics',
    readTime: '3 min read',
    image: '/assets/images/guyana.jpg',
    slug: 'guyana-weekly-2025-11-10',
    tags: ['Guyana', 'Weekly Report', 'Statistics']
  }
];

// State
let currentFilter = 'all';
let currentPage = 1;
const postsPerPage = 9;

// Initialize
document.addEventListener('DOMContentLoaded', () => {
  renderHeader();
  renderPosts();
  setupFilters();
});

function renderPosts() {
  const container = document.getElementById('blog-posts');
  const filteredPosts = filterPosts();
  const paginatedPosts = paginate(filteredPosts);

  if (paginatedPosts.length === 0) {
    container.innerHTML = `
      <div class="col-span-full text-center py-12">
        <p class="text-slate-600 text-lg">No blog posts found for this filter.</p>
      </div>
    `;
    return;
  }

  container.innerHTML = paginatedPosts.map(post => `
    <article class="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-xl transition-shadow">
      <a href="/blog-post.html?slug=${post.slug}" class="block">
        <img src="${post.image}" alt="${post.countryName}" class="w-full h-48 object-cover">
        <div class="p-6">
          <div class="flex items-center gap-2 mb-3">
            <span class="text-xs font-semibold px-2 py-1 rounded bg-rose-100 text-rose-700">
              ${post.countryName}
            </span>
            <span class="text-xs text-slate-500">${formatDate(post.date)}</span>
          </div>
          <h2 class="text-xl font-bold text-slate-900 mb-2 hover:text-rose-600 transition">
            ${post.title}
          </h2>
          <p class="text-slate-600 mb-4 line-clamp-3">${post.excerpt}</p>
          <div class="flex items-center justify-between text-sm text-slate-500">
            <span>${post.author}</span>
            <span>${post.readTime}</span>
          </div>
        </div>
      </a>
    </article>
  `).join('');

  renderPagination(filteredPosts.length);
}

function filterPosts() {
  if (currentFilter === 'all') {
    return blogPosts;
  }
  return blogPosts.filter(post => post.country === currentFilter);
}

function paginate(posts) {
  const start = (currentPage - 1) * postsPerPage;
  const end = start + postsPerPage;
  return posts.slice(start, end);
}

function renderPagination(totalPosts) {
  const totalPages = Math.ceil(totalPosts / postsPerPage);
  const paginationContainer = document.getElementById('pagination');

  if (totalPages <= 1) {
    paginationContainer.classList.add('hidden');
    return;
  }

  paginationContainer.classList.remove('hidden');
  paginationContainer.innerHTML = Array.from({ length: totalPages }, (_, i) => i + 1)
    .map(page => `
      <button
        class="px-4 py-2 rounded-lg font-medium transition ${
          page === currentPage
            ? 'bg-rose-600 text-white'
            : 'bg-slate-200 text-slate-700 hover:bg-slate-300'
        }"
        onclick="window.changePage(${page})"
      >
        ${page}
      </button>
    `).join('');
}

function setupFilters() {
  const filterButtons = {
    'filter-all': 'all',
    'filter-tt': 'tt',
    'filter-gy': 'gy'
  };

  Object.entries(filterButtons).forEach(([buttonId, filter]) => {
    const button = document.getElementById(buttonId);
    button.addEventListener('click', () => {
      currentFilter = filter;
      currentPage = 1;
      updateFilterButtons(buttonId);
      renderPosts();
    });
  });
}

function updateFilterButtons(activeId) {
  ['filter-all', 'filter-tt', 'filter-gy'].forEach(id => {
    const button = document.getElementById(id);
    if (id === activeId) {
      button.classList.remove('bg-slate-200', 'text-slate-700');
      button.classList.add('bg-rose-600', 'text-white');
    } else {
      button.classList.remove('bg-rose-600', 'text-white');
      button.classList.add('bg-slate-200', 'text-slate-700');
    }
  });
}

function formatDate(dateString) {
  const options = { year: 'numeric', month: 'long', day: 'numeric' };
  return new Date(dateString).toLocaleDateString('en-US', options);
}

// Expose changePage to global scope for pagination buttons
window.changePage = (page) => {
  currentPage = page;
  renderPosts();
  window.scrollTo({ top: 0, behavior: 'smooth' });
};
